# Generated by Django 3.0.8 on 2020-07-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_boastsroasts_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsroasts',
            name='boast_or_roast',
            field=models.CharField(choices=[('B', 'Boast'), ('R', 'Roast')], default=None, max_length=1),
        ),
    ]
