# Generated by Django 3.0.8 on 2020-07-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200702_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastsroasts',
            name='secret_id',
        ),
    ]
