# Generated by Django 3.0.8 on 2020-07-02 14:12

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_boastsroasts_secret_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastsroasts',
            name='secret_id',
            field=models.CharField(default=api.utils.private_key, max_length=10),
        ),
    ]
